apiVersion: v1
kind: Pod
metadata:
  name: myconfig-fs-pod
spec:
  containers:
  - name: test-container
    image: gcr.io/google_containers/busybox
    command: [ "/bin/sh", "-c", "cat /etc/myconfig/backend.properties" ]
    volumeMounts:
      - name: configs
        mountPath: /etc/myconfig
        readOnly: true
  volumes:
    - name: configs
      configMap:
        name: myconfig
  restartPolicy: Never
