apiVersion: v1
kind: Pod
metadata:
  name: myconfig-env-pod
spec:
  containers:
  - name: test-container
    image: gcr.io/google_containers/busybox
    command: [ "/bin/sh", "-c", "env" ]
    env:
    - name: CFG_BGCOLOR
      valueFrom:
        configMapKeyRef:
          name: myconfig
          key: bg.color
    - name: CFG_JSON
      valueFrom:
        configMapKeyRef:
          name: myconfig
          key: config.json
  restartPolicy: Never
