apiVersion: v1
kind: Pod
metadata:
  name: mysecret-fs-pod
spec:
  containers:
  - name: test-container
    image: gcr.io/google_containers/busybox
    command: [ "/bin/sh", "-c", "cat /etc/mysecrets/username" ]
    volumeMounts:
      - name: "secrets"
        mountPath: "/etc/mysecrets"
        readOnly: true
  volumes:
    - name: "secrets"
      secret:
        secretName: "mysecret"
  restartPolicy: Never
